apiVersion: v1
kind: Pod
metadata:
  name: gec-pd
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: my-own-disk
      fsType: ext4