apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: nginx
    tier: dev
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: redis-container
    image: redis