apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1.0
  labels:
    app: nginx-1.0
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1.0
      env: prod
  template:
    metadata:
      labels:
        app: nginx-1.0
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer